site_name: Baga Ivy Generator
nav:
  - Home: index.md

  - Getting Started: 
      - Installation: getting-started/installation.md
      - First Steps (Workflow): getting-started/workflow.md
      - Generation Modes: getting-started/modes.md

  - Procedural Mode :
    - Create Ivy :
        - Add New Ivy: procedural/creation/create-ivy.md
        - Draw Mode: procedural/creation/drawing.md
    - Parameters :
        - Growth & Branching: procedural/parameters/growth.md
        - Leavess & Flowers: procedural/parameters/leaves.md
    - Advanced Features:
        - Effectors (Obstacles): procedural/advanced/effectors.md
        - Animation: procedural/advanced/animation.md
        - Optimization: procedural/advanced/performance.md
        - Advanced Generation: procedural/advanced/generation-settings.md
    - Management:
        - Source Objects: procedural/management/sources.md
        - Apply & Export: procedural/management/apply-mesh.md

  - Simulation Mode :
    - Create Ivy :
        - Add New Ivy: simulation/creation/create-ivy.md
        - Baking: simulation/creation/bake.md
        - Step 1 - Core Growth: simulation/creation/step-1.md
        - Step 2 - Foliage Growth: simulation/creation/step-2.md
    - Features :
        - Draw Control: simulation/features/draw.md
        - Cut Tool: simulation/features/cut.md
        - Leaves & Flowers: simulation/features/leaves.md
        - Animation: simulation/features/animation.md
        - Optimization: simulation/features/optimization.md
        - Visibility: simulation/features/visibility.md
    - Management:
        - Objects Data: simulation/management/sources.md
        - Apply & Export: simulation/management/apply-mesh.md

  - Help & Support: support.md

theme: readthedocs